name: earthcube
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - cartopy
  - netCDF4
  - xarray
  - pip:
    - pillow==8.2.0
    - matplotlib==3.2.2
    - git+https://github.com/Weiming-Hu/PyAnEn.git
