name: earthcube
channels:
  - conda-forge
dependencies:
  - PIL==7.1.2
  - numpy
  - pandas
  - cartopy
  - matplotlib
  - netCDF4
  - xarray
  - properscoring
  - pip:
    - git+https://github.com/Weiming-Hu/PyAnEn.git
