name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - cartopy
  - matplotlib
  - pip
  - netCDF4
  - xarray
  - properscoring
  - pip:
    - git+https://github.com/Weiming-Hu/PyAnEn.git
