name: earthcube
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - partd
  - bokeh
  - dask
  - pandas
  - cartopy
  - netCDF4
  - xarray
  - properscoring
  - pip:
    - git+https://github.com/Weiming-Hu/PyAnEn.git
